// Application constants
export const DEPARTMENTS = [
  'General',
  'Pediatrics', 
  'Dentistry',
];

export const DEPARTMENT_TRANSLATIONS = {
  en: {
    general: 'General',
    pediatrics: 'Pediatrics',
    dentistry: 'Dentistry',
  },
  ru: {
    general: 'Общее',
    pediatrics: 'Педиатрия',
    dentistry: 'Стоматология',
  },
  kg: {
    general: 'Жалпы',
    pediatrics: 'Педиатрия',
    dentistry: 'Стоматология',
  },
};

export const LANGUAGES = {
  en: 'English',
  ru: 'Русский',
  kg: 'Кыргызча',
};

export const TEXT_TRANSLATIONS = {
  en: {
    // Common
    register: "Register",
    login: "Login",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    help: "Help",
    home: "Home",
    
    // Clinic branding
    clinicName: "Naryn Clinic",
    
    // Home page
    title: "Naryn Clinic Queue System",
    subtitle: "Professional appointment scheduling and queue management",
    patientRegistration: "Patient Registration",
    doctorLogin: "Doctor Login",
    dailyPatients: "Daily Patients",
    departments: "Departments", 
    medicalStaff: "Medical Staff",
    
    // Login page
    doctorDashboard: "Doctor Login",
    username: "Username",
    password: "Password",
    wrongCredentials: "Wrong credentials",
    enterUsername: "Enter your username",
    enterPassword: "Enter your password",
    demoCredentials: "Demo Credentials",
    demoUsername: "doctor",
    demoPassword: "1234",
    
    // Patient page
    registerPatient: "Register Patient",
    fullName: "Full Name",
    department: "Department",
    time: "Time (HH:MM)",
    day: "Day",
    yourQueueNumber: "Your Queue Number",
    position: "Position",
    status: "Status",
    confirmDeleteSlot: "Are you sure you want to delete this time slot?",
    addNewTimeSlot: "Add New Time Slot",
    maxPatients: "Max Patients",
    addSlot: "Add Slot",
    noTimeSlotsFound: "No Time Slots Found",
    noTimeSlotsConfigured: "No time slots configured for",
    bookings: "Bookings",
    open: "Open",
    closed: "Closed",
    close: "Close",
    deleteSlot: "Delete Slot",
    cannotDeleteBookedSlot: "Cannot delete a slot that already has bookings",
    noPatientsFound: "No Patients Found",
    noPatientsScheduled: "No patients scheduled for",
    startConsultation: "Start Consultation",
    complete: "Complete",
    
    // Doctor page
    doctorDashboardTitle: "Doctor Dashboard",
    loadPatients: "Load Patients",
    callNext: "Call Next",
    switchLanguage: "Switch Language",
    
    // Help Modal
    helpTitle: "Help & Support",
    contactInfo: "Contact Information",
    phone: "Phone",
    email: "Email",
    address: "Address",
    hours: "Working Hours",
    quickLinks: "Quick Links",
    workingHours: "Working Hours",
    clinicDescription: "Professional healthcare management for modern clinics",
    mondayFriday: "Mon-Fri: 8:00 AM - 6:00 PM",
    saturday: "Sat: 9:00 AM - 2:00 PM",
    sunday: "Sunday: Closed",
    doctorPortal: "Doctor Portal",
    manageAppointments: "Manage appointments and patient queues",
    secureReliable: "Secure & Reliable",
    professionalHealthcare: "Professional healthcare management system",
    availableTimeSlots: "Available Time Slots",
    loadingTimeSlots: "Loading available time slots...",
    appointmentConfirmed: "Appointment Confirmed",
    queueNumber: "Queue Number",
    department: "Department",
    day: "Day",
    time: "Time",
    status: "Status",
    frequentlyAskedQuestions: "Frequently Asked Questions",
    emergencyTitle: "Emergency Contact",
    emergencyText: "For medical emergencies, please call immediately",
    callNow: "Call Now",
    
    // FAQ
    faqQueueQuestion: "How does the queue system work?",
    faqQueueAnswer: "Simply register as a patient, select your department and preferred time. You'll receive a queue number and can track your position in real-time.",
    faqRegistrationQuestion: "What information do I need to register?",
    faqRegistrationAnswer: "You'll need your full name, preferred department, appointment time, and date. The process takes less than a minute.",
    faqDoctorQuestion: "How do doctors use the system?",
    faqDoctorAnswer: "Doctors can log in with their credentials, view patient queues for any day, and call the next patient in line with a single click.",
  },
  ru: {
    // Common
    register: "Зарегистрироваться",
    login: "Войти",
    loading: "Загрузка...",
    error: "Ошибка",
    success: "Успешно",
    help: "Помощь",
    home: "Главная",
    
    // Clinic branding
    clinicName: "Нарынская клиника",
    
    // Home page
    title: "Система очереди Нарынской клиники",
    subtitle: "Профессиональное планирование записей и управление очередью",
    patientRegistration: "Регистрация пациента",
    doctorLogin: "Вход врача",
    dailyPatients: "Ежедневные пациенты",
    departments: "Отделения", 
    medicalStaff: "Медицинский персонал",
    
    // Login page
    doctorDashboard: "Панель врача",
    username: "Имя пользователя",
    password: "Пароль",
    wrongCredentials: "Неверные учетные данные",
    enterUsername: "Введите ваше имя пользователя",
    enterPassword: "Введите ваш пароль",
    demoCredentials: "Демо учетные данные",
    demoUsername: "doctor",
    demoPassword: "1234",
    
    // Patient page
    registerPatient: "Регистрация пациента",
    fullName: "Полное имя",
    department: "Отделение",
    time: "Время (ЧЧ:ММ)",
    day: "День",
    yourQueueNumber: "Ваш номер очереди",
    position: "Позиция",
    status: "Статус",
    confirmDeleteSlot: "Вы уверены, что хотите удалить этот временной слот?",
    addNewTimeSlot: "Добавить новый слот",
    maxPatients: "Макс. пациентов",
    addSlot: "Добавить слот",
    noTimeSlotsFound: "Временные слоты не найдены",
    noTimeSlotsConfigured: "Нет настроенных слотов для",
    bookings: "Бронирования",
    open: "Открыто",
    closed: "Закрыто",
    close: "Закрыть",
    deleteSlot: "Удалить слот",
    cannotDeleteBookedSlot: "Нельзя удалить слот с активными бронированиями",
    noPatientsFound: "Пациенты не найдены",
    noPatientsScheduled: "Нет запланированных пациентов на",
    startConsultation: "Начать консультацию",
    complete: "Завершить",
    
    // Doctor page
    doctorDashboardTitle: "Панель врача",
    loadPatients: "Загрузить пациентов",
    callNext: "Следующий",
    switchLanguage: "Сменить язык",
    
    // Help Modal
    helpTitle: "Помощь и поддержка",
    contactInfo: "Контактная информация",
    phone: "Телефон",
    email: "Email",
    address: "Адрес",
    hours: "Часы работы",
    quickLinks: "Быстрые ссылки",
    workingHours: "Время работы",
    clinicDescription: "Профессиональное управление здравоохранением для современных клиник",
    mondayFriday: "Пн-Пт: 8:00 - 18:00",
    saturday: "Сб: 9:00 - 14:00",
    sunday: "Вс: Закрыто",
    doctorPortal: "Портал врача",
    manageAppointments: "Управление записями и очередями пациентов",
    secureReliable: "Безопасный и надежный",
    professionalHealthcare: "Профессиональная система управления здравоохранением",
    availableTimeSlots: "Доступные временные слоты",
    loadingTimeSlots: "Загрузка доступных временных слотов...",
    appointmentConfirmed: "Запись подтверждена",
    queueNumber: "Номер очереди",
    department: "Отделение",
    day: "День",
    time: "Время",
    status: "Статус",
    frequentlyAskedQuestions: "Часто задаваемые вопросы",
    emergencyTitle: "Экстренный контакт",
    emergencyText: "Для медицинских экстренных случаев, пожалуйста, звоните немедленно",
    callNow: "Позвонить сейчас",
    
    // FAQ
    faqQueueQuestion: "Как работает система очереди?",
    faqQueueAnswer: "Просто зарегистрируйтесь как пациент, выберите отделение и предпочтительное время. Вы получите номер очереди и сможете отслеживать свою позицию в реальном времени.",
    faqRegistrationQuestion: "Какая информация нужна для регистрации?",
    faqRegistrationAnswer: "Вам понадобятся полное имя, предпочтительное отделение, время приема и дата. Процесс занимает меньше минуты.",
    faqDoctorQuestion: "Как врачи используют систему?",
    faqDoctorAnswer: "Врачи могут войти со своими учетными данными, просматривать очереди пациентов на любой день и вызывать следующего пациента в очереди одним нажатием.",
  },
  kg: {
    // Common
    register: "Катталуу",
    login: "Кирүү",
    loading: "Жүктөлүүдө...",
    error: "Ката",
    success: "Ийгилик",
    help: "Жардам",
    home: "Башкы",
    
    // Clinic branding
    clinicName: "Нарын клиникасы",
    
    // Home page
    title: "Нарын клиникасынын системасы",
    subtitle: "Профессионалдык жазууларды пландоо жана кезекти башкаруу",
    patientRegistration: "Пациентти каттоо",
    doctorLogin: "Дарыгер кирүүсү",
    dailyPatients: "Күнүмдүк пациенттер",
    departments: "Бөлүмдөр", 
    medicalStaff: "Медициналык кызматкерлер",
    
    // Login page
    doctorDashboard: "Дарыгер кирүүсү",
    username: "Колдонуучу аты",
    password: "Сырсөз",
    wrongCredentials: "Туура эмес жөнөтүүлөр",
    enterUsername: "Колдонуучу атыңызды киргиңүз",
    enterPassword: "Сырсөзүңүз киргиңүз",
    demoCredentials: "Демо жөнөтүүлөр",
    demoUsername: "doctor",
    demoPassword: "1234",
    
    // Patient page
    registerPatient: "Пациентти каттоо",
    fullName: "Толук аты",
    department: "Бөлүм",
    time: "Убакыт (ЧЧ:ММ)",
    day: "Күн",
    yourQueueNumber: "Сиздин номериңиз",
    position: "Орду",
    status: "Абалы",
    confirmDeleteSlot: "Бул убакытты өчүрүүнү каалайсызбы?",
    addNewTimeSlot: "Жаңы убакыт кошуу",
    maxPatients: "Макс. пациенттер",
    addSlot: "Кошуу",
    noTimeSlotsFound: "Бош убакыттар табылган жок",
    noTimeSlotsConfigured: "Бул күнгө убакыттар жок:",
    bookings: "Каттоолор",
    open: "Ачык",
    closed: "Жабык",
    close: "Жабуу",
    deleteSlot: "Өчүрүү",
    cannotDeleteBookedSlot: "Каттоосу бар убакытты өчүрүүгө болбойт",
    noPatientsFound: "Пациенттер табылган жок",
    noPatientsScheduled: "Бул күнгө пациенттер жок:",
    startConsultation: "Кабыл алууну баштоо",
    complete: "Аяктоо",
    
    // Doctor page
    doctorDashboardTitle: "Дарыгер панели",
    loadPatients: "Пациенттерди жүктөө",
    callNext: "Кийинкиси",
    switchLanguage: "Тилди өзгөртүү",
    
    // Help Modal
    helpTitle: "Жардам жана колдоо",
    contactInfo: "Байланыш маалыматы",
    phone: "Телефон",
    email: "Email",
    address: "Дареги",
    hours: "Иш убактысы",
    quickLinks: "Тез шилтемелер",
    workingHours: "Иш убактысы",
    clinicDescription: "Замана клиникалар үчүн профессионалдык башкаруу",
    mondayFriday: "Дүй-Жума: 8:00 - 18:00",
    saturday: "Ишембе: 9:00 - 14:00",
    sunday: "Жекшемби: Дем алыш куну",
    doctorPortal: "Дарыгер порталы",
    manageAppointments: "Каттоолорду жана кезекти башкаруу",
    secureReliable: "Коопсуз жана ишенимдүү",
    professionalHealthcare: "Профессионалдык ден соолук башкаруу системасы",
    availableTimeSlots: "Бош убакыттар",
    loadingTimeSlots: "Бош убакыттарды жүктөө...",
    appointmentConfirmed: "Каттоо тастыкталды",
    queueNumber: "Кезек номур",
    department: "Бөлүм",
    day: "Күн",
    time: "Убакыт",
    status: "Абалы",
    frequentlyAskedQuestions: "Көп суралган суроолор",
    emergencyTitle: "Күтүлбөгөн байланыш",
    emergencyText: "Медициналык күтүлбөгөн учурлар үчүн, тез ара байланышыңыз",
    callNow: "Азыр чалуу",
    
    // FAQ
    faqQueueQuestion: "Кезек системасы кантип иштейт?",
    faqQueueAnswer: "Жөн эле пациент каттап, бөлүмүңүздү жана каалаган убактыңызды тандаңыз. Кезек номери алып, позицияңызды реал убакытта көзө аласыз.",
    faqRegistrationQuestion: "Каттоо үчүн кайсы маалымат керек?",
    faqRegistrationAnswer: "Сизге толук атыңыз, каалаган бөлүмүңүз, кабыл алуу убактыңыз жана күнү керек. Процесс бир минуттан аз убакытты алат.",
    faqDoctorQuestion: "Дарыгерлер системаны кантип колдонушат?",
    faqDoctorAnswer: "Дарыгерлер өз эсептөө маалыматтары менен кире алышат, кайсы күн болбосун пациенттердин кезегин көрө алышат жана кезектеги пациентти бир басуу менен чакыра алышат.",
  },
};

export const UPDATE_INTERVAL = 3000; // 3 seconds

export const STATUS_COLORS = {
  'Waiting': 'status-waiting',
  'In Progress': 'status-in-progress',
  'Completed': 'status-completed',
};
